[package]
name = "list2choice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.18.0"
rayon = "1.5.1"
static_init = "1.0.2"
